services:

  twl2-pg:
    container_name: twl2-pg-staging
    networks:
      - twl2-staging-network
    env_file:
      - ../Moodle-Secrets/staging.env
    volumes: 
      - twl2-pg-staging:/var/lib/postgresql/data

  twl2-site:
    container_name: twl2-site-staging
    networks:
      - twl2-staging-network
    env_file:
      - ../Moodle-Secrets/staging.env
    volumes:
      - ../moodledata/Staging/:/var/www/moodledata 
    depends_on:
      - twl2-pg
  
  twl2-gateway:
    container_name: twl2-gateway-staging
    networks:
      - twl2-staging-network
    ports:
      - 80:80
    volumes:
      - ./_docker/nginx/conf.d/nginx.staging.conf:/etc/nginx/nginx.conf
      - ../moodledata/Staging/:/var/www/moodledata 

volumes:
  twl2-pg-staging:

networks:
  twl2-staging-network:
    name: twl2-staging-network
    driver: bridge
