services:

  twl2-pg:
    container_name: twl2-pg-dev
    networks:
      - twl2-dev-network
    env_file:
      - ./.env
    volumes: 
      - twl2-pg-data-dev:/var/lib/postgresql/data

  twl2-site:
    container_name: twl2-site-dev
    networks:
      - twl2-dev-network
    env_file:
      - ./.env
    volumes:
      - ./_docker/moodledata:/var/www/moodledata 
      - ./:/var/www/html      
    depends_on:
      - twl2-pg
  
  twl2-gateway:
    container_name: twl2-gateway-dev
    networks:
      - twl2-dev-network
    ports:
      - 8080:80
    volumes:
      - ./_docker/nginx/conf.d/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./_docker/moodledata:/var/www/moodledata 
      - ./:/var/www/html      

networks:
  twl2-dev-network:
    name: twl2-dev-network
    driver: bridge

volumes:
  twl2-pg-data-dev:
    driver: local
