services:

  twl2-pg:
    container_name: twl2-pg-production
    networks:
      - twl2-production-network
    env_file:
      - ../Moodle-Secrets/production.env
    volumes: 
      - twl2-pg-production:/var/lib/postgresql/data

  twl2-site:
    container_name: twl2-site-production
    networks:
      - twl2-production-network
    env_file:
      - ../Moodle-Secrets/production.env
    volumes:
      - ../moodledata/Production/:/var/www/moodledata 
    depends_on:
      - twl2-pg
  
  twl2-gateway:
    container_name: twl2-gateway-production
    networks:
      - twl2-production-network
    volumes:
      - ./_docker/nginx/conf.d/nginx.production.conf:/etc/nginx/nginx.conf
      - ../moodledata/Production/:/var/www/moodledata 

volumes:
  twl2-pg-production:

networks:
  twl2-production-network:
    name: twl2-production-network
    driver: bridge
